version: 2
updates:
  # Maintain dependencies for hex
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/assets/"
    schedule:
      interval: "weekly"
