on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [25.0.0]
        elixir: [1.14.5]
    env:
      MIX_ENV: dev 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: tenantee 
          POSTGRES_PASSWORD: tenantee
          POSTGRES_DB: tenantee_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix credo
      - run: mix sobelow
      - run: mix ecto.create && mix ecto.migrate
      - run: mix coveralls.github
